### PR TITLE
Fix segfault and iterator error

### PR DESCRIPTION
**Pull request by jirutka**
The current version 1.2.3 segfaults on calling `open_simple()`. You can see logs from tests (see #2) for all Lua versions [here](https://travis-ci.org/jirutka/lualdap/builds/210152047).

When I fixed it, another error has appeared, caused by 2867f1f76321fe3832d19ee309b80be0bccaba1d:

    tests/test.lua:175: bad argument #1 to 'iter' (table expected, got no value)

You can see logs [here](https://travis-ci.org/jirutka/lualdap/builds/210152789).

And finally logs from green builds with both #1 and #2 applied are [here](https://travis-ci.org/jirutka/lualdap/builds/210152235). As you can see, tests passes even on Lua 5.3, so you can remove the upper bound for Lua version in rockspec (currently there’s `lua >= 5.1, < 5.3`).

/cc @devurandom

### CODE REVIEW

**Comment by devurandom** [comment]
It's been a while since I lasted looked at this code, so please excuse me, if the answer seems obvious: Why is calling the iterator without a state legal? I think I specifically inserted that check, to catch bugs in `lualdap_search`. Also, I am pretty sure this code worked once - I was actually using this... Are you sure that nothing else changed in your version, that might have changed the conditions under which `next_message` is being called?

The segfault fix seems good. Much better than the bunch of code we had before.

**Comment by jirutka** [comment]
> Why is calling the iterator without a state legal?

To be honest, I don’t know. But as you can clearly see in [logs on Travis](https://travis-ci.org/jirutka/lualdap/builds/210152789), the included tests fail on Lua 5.1, 5.2, 5.3, LuaJIT 2.0 and LuaJIT 2.1. It fails both on up-to-date Alpine Linux (musl libc, openldap 2.4.44), ancient Ubuntu Precise (glibc, openldap 2.4.28) and Trusty (glibc, openldap 2.4.31) on Travis CI. Have you ever run these tests…?

> Are you sure that nothing else changed in your version.

How? It’s in git, you can examine my patches and all previous commits. I really haven’t created a SHA-1 collision and compromised the repository just to confuse you…

* * *

I just found out yet another error – anonymous bind doesn’t work (and there are no tests for it now)! I really wonder how have you and @bdellegrazie tested your changes…

**Comment by jirutka** [comment]
@bdellegrazie @devurandom gentle ping

**Comment by bdellegrazie** [comment]
@jirutka: Sorry I've been on holiday and only just returned. I'm little jet lagged and will get to this within the next week.

**Comment by bdellegrazie** [comment]
@jirutka: I've just added a Travis CI setup to master, would you please rebase your change on top of master? It should be a trivial rebase as I haven't made any code changes.
Thanks!

**Comment by jirutka** [comment]
I’ve rebased it, but I don’t understand why you haven’t simple merged #2 that (among others) adds configuration for Travis and instead reinvented it yourself (just worse, it’s even not fully working)…

**Comment by bdellegrazie** [comment]
@jirutka: I had really only looked at the first PR, not the second, otherwise I wouldn't have.
I'll revert my changes and merge yours instead.

**Comment by jirutka** [comment]
Could you please release a new version to LuaRocks (1.2.4 according to semver)?

**Pull request merged**
